### ISSUE TITLE
The CustomResourceDefinition "fluxes.flux.codesink.net" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{

### ISSUE THREAD

**Issue by floriankoch** [justinbarrick/flux-operator#33]
Hi, trying to apply the Flux operator (flux-operator-namespaced.yaml or fluxoptctl) against a Kubernetes 1.10.4 Cluster , got the Error:
The CustomResourceDefinition "fluxes.flux.codesink.net" is invalid: spec.validation.openAPIV3Schema: 
...

Full error log is attached
[error.log](https://github.com/justinbarrick/flux-operator/files/2568544/error.log)

**Comment by justinbarrick** [comment]
This is resolved now.
